-- Wyckoff Analysis Supabase schema
-- Idempotent setup for the tables referenced by core/constants.py.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  feishu_webhook text default '',
  wecom_webhook text default '',
  dingtalk_webhook text default '',
  chat_provider text default 'gemini',
  gemini_api_key text default '',
  gemini_model text default '',
  gemini_base_url text default '',
  openai_api_key text default '',
  openai_model text default '',
  openai_base_url text default '',
  deepseek_api_key text default '',
  deepseek_model text default '',
  deepseek_base_url text default '',
  zhipu_api_key text default '',
  zhipu_model text default '',
  zhipu_base_url text default '',
  minimax_api_key text default '',
  minimax_model text default '',
  minimax_base_url text default '',
  qwen_api_key text default '',
  qwen_model text default '',
  qwen_base_url text default '',
  volcengine_api_key text default '',
  volcengine_model text default '',
  volcengine_base_url text default '',
  custom_providers jsonb default '{}'::jsonb,
  tushare_token text default '',
  tickflow_api_key text default '',
  tg_bot_token text default '',
  tg_chat_id text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_hist_cache (
  symbol text not null,
  adjust text not null default 'qfq',
  date date not null,
  open numeric,
  high numeric,
  low numeric,
  close numeric,
  volume numeric,
  amount numeric,
  pct_chg numeric,
  updated_at timestamptz not null default now(),
  primary key (symbol, adjust, date)
);

create table if not exists public.market_signal_daily (
  trade_date date primary key,
  benchmark_regime text,
  main_index_code text,
  main_index_close numeric,
  main_index_ma50 numeric,
  main_index_ma200 numeric,
  main_index_recent3_cum_pct numeric,
  main_index_today_pct numeric,
  smallcap_index_code text,
  smallcap_close numeric,
  smallcap_recent3_cum_pct numeric,
  premarket_regime text,
  premarket_reasons jsonb default '[]'::jsonb,
  a50_value_date date,
  a50_source text,
  a50_close numeric,
  a50_pct_chg numeric,
  vix_value_date date,
  vix_source text,
  vix_close numeric,
  vix_pct_chg numeric,
  benchmark_slot text,
  premarket_slot text,
  market_posture_code text,
  market_posture_name text,
  wind_phrase text,
  water_phrase text,
  action_phrase text,
  banner_tone text,
  banner_title text,
  banner_message text,
  source_jobs jsonb default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.recommendation_tracking (
  id bigint generated by default as identity primary key,
  code integer not null,
  name text default '',
  recommend_reason text default '',
  recommend_date integer not null,
  initial_price numeric default 0,
  current_price numeric default 0,
  change_pct numeric default 0,
  recommend_count integer default 1,
  funnel_score numeric,
  is_ai_recommended boolean default false,
  camp text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (code, recommend_date)
);

create table if not exists public.job_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  job_kind text not null,
  usage_date date not null,
  count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, job_kind, usage_date)
);

create table if not exists public.user_tier (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null default 'free',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.signal_pending (
  id bigint generated by default as identity primary key,
  code integer not null,
  name text default '',
  signal_type text not null,
  signal_date date not null,
  signal_score numeric default 0,
  status text not null default 'pending',
  ttl_days integer default 3,
  days_elapsed integer default 0,
  regime text default '',
  industry text default '',
  snap_open numeric,
  snap_high numeric,
  snap_low numeric,
  snap_close numeric,
  snap_volume numeric,
  snap_ma20 numeric,
  snap_ma50 numeric,
  snap_support numeric,
  confirm_reason text default '',
  confirm_date date,
  expire_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (code, signal_type, signal_date)
);

create table if not exists public.portfolios (
  portfolio_id text primary key,
  name text default 'Real Portfolio',
  free_cash numeric not null default 0,
  total_equity numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_positions (
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  code text not null,
  name text default '',
  shares integer not null default 0,
  cost_price numeric not null default 0,
  buy_dt text default '',
  stop_loss numeric,
  strategy text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, code)
);

create table if not exists public.trade_orders (
  id bigint generated by default as identity primary key,
  run_id text not null,
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  trade_date date not null,
  model text default '',
  market_view text default '',
  code text not null,
  name text default '',
  action text default '',
  status text default '',
  shares integer default 0,
  price_hint numeric,
  amount numeric default 0,
  stop_loss numeric,
  max_loss numeric default 0,
  drawdown_ratio numeric default 0,
  reason text default '',
  tape_condition text default '',
  invalidate_condition text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_nav (
  portfolio_id text not null references public.portfolios(portfolio_id) on delete cascade,
  trade_date date not null,
  free_cash numeric not null default 0,
  positions_value numeric not null default 0,
  total_equity numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (portfolio_id, trade_date)
);

create index if not exists idx_stock_hist_cache_symbol_date on public.stock_hist_cache(symbol, adjust, date desc);
create index if not exists idx_market_signal_daily_updated on public.market_signal_daily(updated_at desc);
create index if not exists idx_recommendation_tracking_date on public.recommendation_tracking(recommend_date desc);
create index if not exists idx_recommendation_tracking_code on public.recommendation_tracking(code);
create index if not exists idx_signal_pending_status_date on public.signal_pending(status, signal_date desc);
create index if not exists idx_signal_pending_code_type on public.signal_pending(code, signal_type);
create index if not exists idx_portfolios_updated on public.portfolios(updated_at desc);
create index if not exists idx_trade_orders_portfolio_date on public.trade_orders(portfolio_id, trade_date desc);
create index if not exists idx_trade_orders_run on public.trade_orders(run_id);
create index if not exists idx_daily_nav_portfolio_date on public.daily_nav(portfolio_id, trade_date desc);

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
before update on public.user_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_recommendation_tracking_updated_at on public.recommendation_tracking;
create trigger trg_recommendation_tracking_updated_at
before update on public.recommendation_tracking
for each row execute function public.set_updated_at();

drop trigger if exists trg_job_usage_updated_at on public.job_usage;
create trigger trg_job_usage_updated_at
before update on public.job_usage
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_tier_updated_at on public.user_tier;
create trigger trg_user_tier_updated_at
before update on public.user_tier
for each row execute function public.set_updated_at();

drop trigger if exists trg_signal_pending_updated_at on public.signal_pending;
create trigger trg_signal_pending_updated_at
before update on public.signal_pending
for each row execute function public.set_updated_at();

drop trigger if exists trg_portfolios_updated_at on public.portfolios;
create trigger trg_portfolios_updated_at
before update on public.portfolios
for each row execute function public.set_updated_at();

drop trigger if exists trg_portfolio_positions_updated_at on public.portfolio_positions;
create trigger trg_portfolio_positions_updated_at
before update on public.portfolio_positions
for each row execute function public.set_updated_at();

alter table public.user_settings enable row level security;
alter table public.stock_hist_cache enable row level security;
alter table public.market_signal_daily enable row level security;
alter table public.recommendation_tracking enable row level security;
alter table public.job_usage enable row level security;
alter table public.user_tier enable row level security;
alter table public.signal_pending enable row level security;
alter table public.portfolios enable row level security;
alter table public.portfolio_positions enable row level security;
alter table public.trade_orders enable row level security;
alter table public.daily_nav enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on public.stock_hist_cache to anon;
grant select on public.market_signal_daily to anon;
grant select on public.recommendation_tracking to anon;
grant select on public.signal_pending to anon;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "user_settings_select_own" on public.user_settings;
create policy "user_settings_select_own" on public.user_settings
for select using (user_id = auth.uid());

drop policy if exists "user_settings_insert_own" on public.user_settings;
create policy "user_settings_insert_own" on public.user_settings
for insert with check (user_id = auth.uid());

drop policy if exists "user_settings_update_own" on public.user_settings;
create policy "user_settings_update_own" on public.user_settings
for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "stock_hist_cache_public_read" on public.stock_hist_cache;
create policy "stock_hist_cache_public_read" on public.stock_hist_cache
for select using (true);

drop policy if exists "stock_hist_cache_authenticated_write" on public.stock_hist_cache;
create policy "stock_hist_cache_authenticated_write" on public.stock_hist_cache
for all to authenticated using (true) with check (true);

drop policy if exists "market_signal_daily_public_read" on public.market_signal_daily;
create policy "market_signal_daily_public_read" on public.market_signal_daily
for select using (true);

drop policy if exists "recommendation_tracking_public_read" on public.recommendation_tracking;
create policy "recommendation_tracking_public_read" on public.recommendation_tracking
for select using (true);

drop policy if exists "signal_pending_public_read" on public.signal_pending;
create policy "signal_pending_public_read" on public.signal_pending
for select using (true);

drop policy if exists "job_usage_select_own" on public.job_usage;
create policy "job_usage_select_own" on public.job_usage
for select using (user_id = auth.uid());

drop policy if exists "job_usage_insert_own" on public.job_usage;
create policy "job_usage_insert_own" on public.job_usage
for insert with check (user_id = auth.uid());

drop policy if exists "job_usage_update_own" on public.job_usage;
create policy "job_usage_update_own" on public.job_usage
for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "user_tier_select_own" on public.user_tier;
create policy "user_tier_select_own" on public.user_tier
for select using (user_id = auth.uid());

drop policy if exists "portfolios_select_own" on public.portfolios;
create policy "portfolios_select_own" on public.portfolios
for select using (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolios_insert_own" on public.portfolios;
create policy "portfolios_insert_own" on public.portfolios
for insert with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolios_update_own" on public.portfolios;
create policy "portfolios_update_own" on public.portfolios
for update using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolio_positions_select_own" on public.portfolio_positions;
create policy "portfolio_positions_select_own" on public.portfolio_positions
for select using (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolio_positions_insert_own" on public.portfolio_positions;
create policy "portfolio_positions_insert_own" on public.portfolio_positions
for insert with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolio_positions_update_own" on public.portfolio_positions;
create policy "portfolio_positions_update_own" on public.portfolio_positions
for update using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "portfolio_positions_delete_own" on public.portfolio_positions;
create policy "portfolio_positions_delete_own" on public.portfolio_positions
for delete using (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "trade_orders_select_own" on public.trade_orders;
create policy "trade_orders_select_own" on public.trade_orders
for select using (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "trade_orders_update_own" on public.trade_orders;
create policy "trade_orders_update_own" on public.trade_orders
for update using (portfolio_id = ('USER_LIVE:' || auth.uid()::text))
with check (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

drop policy if exists "daily_nav_select_own" on public.daily_nav;
create policy "daily_nav_select_own" on public.daily_nav
for select using (portfolio_id = ('USER_LIVE:' || auth.uid()::text));

notify pgrst, 'reload schema';
